remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme

title: Nevvo Blog
description: Think Tank 4.0 da Nevvo: Blog sobre Inteligência Artificial Aplicada, Tecnologia, Business Intelligence e Marketing Digital 4.0
author:
  name: Nevvo Labs
  email: contato@nevvo.com.br
  social:
    instagram: https://www.instagram.com/nevvolabs/
    youtube: https://www.youtube.com/@NevvoLabs
    tiktok: https://www.tiktok.com/@nevvolabs
    twitter: https://x.com/NevvoLabs
    facebook: https://www.facebook.com/profile.php?id=61568548946429
    github: nevvolabs

# Configurações de aparência
theme_settings:
  show_author_profile: true
  show_excerpt: true
  show_read_time: true

# Configurações avançadas (opcional)
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
